id: 990002
iteration: 0
description: "tiny cifar10 smoke test"

use_saved_topology: false
topology_file: "../data/topologies/smoke/small_world_cifar10.json"

nodes: 4
num_workers: 1
rounds: 2
synchronous: true
device: "cuda:2"

topology: "small-world"
small_world_k: 2
small_world_beta: 0.0
scale_free_m: 1
edge_density: 1.0

malicious_proportion: 0.0
attack_type: "noise"
attack_args:
  strength: 10

aggregation: "fedavg"
trimmed_mean_beta: 0.2

dataset: "cifar10"
dataset_kwargs:
  data_dir: "../data/datasets"
  download: true

model_ckpt_dir: "../data/ckpts"
model_name: "cifar10"
results_dir: "../data/results"

num_samples: 8
epochs_per_round: 1
batch_size: 4
